name: PHP CI Checks

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  php-checks:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        tools: composer

    - name: Check PHP version
      run: php --version

    - name: Check PHP syntax
      run: |
        # Verificar sintaxis de todos los archivos PHP
        find . -name "*.php" -not -path "./vendor/*" -exec php -l {} \; | grep -v "No syntax errors detected"
        
        # Contar archivos PHP para verificación
        echo "Total archivos PHP encontrados:"
        find . -name "*.php" -not -path "./vendor/*" | wc -l

    - name: Run basic PHP tests
      run: |
        # Verificar que los archivos principales existan y sean accesibles
        if [ -f "index.php" ]; then
          echo "index.php encontrado"
          php -l index.php
        else
          echo "index.php no encontrado"
          exit 1
        fi
        
        if [ -f "config.php" ]; then
          echo "config.php encontrado"
          php -l config.php
        fi
        
        # Verificar sintaxis de directorios importantes
        for dir in controlador modelo vista; do
          if [ -d "$dir" ]; then
            echo "Verificando sintaxis en $dir/"
            find "$dir" -name "*.php" -exec php -l {} \; | grep -v "No syntax errors detected"
          fi
        done

    - name: Check for common issues
      run: |
        # Verificar que no haya errores de inclusión básicos
        echo "Buscando posibles problemas..."
        
        # Verificar includes/requires
        grep -r "include\|require" controlador/ modelo/ vista/ 2>/dev/null || echo "No se encontraron includes"
        
        # Verificar que no haya syntax errors críticos
        echo "Verificación básica completada"
